/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Rectangle3584Image from 'src/assets/images/uduXDesktopPlayerWeb_Rectangle_3584.png';
import Rectangle35841Image from 'src/assets/images/uduXDesktopPlayerWeb_Rectangle_3584_1.png';
import Rectangle3850Image from 'src/assets/images/uduXDesktopPlayerWeb_Rectangle_3850.png';
import Rectangle35842Image from 'src/assets/images/uduXDesktopPlayerWeb_Rectangle_3584_2.png';
import Rectangle35843Image from 'src/assets/images/uduXDesktopPlayerWeb_Rectangle_3584_3.png';
import Rectangle3856Image from 'src/assets/images/uduXDesktopPlayerWeb_Rectangle_3856.png';
import MaskGroupImage from 'src/assets/images/uduXDesktopPlayerWeb_Mask_group.png';
import Rectangle3442Image from 'src/assets/images/uduXDesktopPlayerWeb_Rectangle_3442.png';
import Line47Image from 'src/assets/images/uduXDesktopPlayerWeb_Line_47.png';
import VectorImage from 'src/assets/images/uduXDesktopPlayerWeb_Vector.png';
import Vector1Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_1.png';
import Vector2Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_2.png';
import Vector3Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_3.png';
import Vector4Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_4.png';
import Ellipse17593Image from 'src/assets/images/uduXDesktopPlayerWeb_Ellipse_17593.png';
import Vector5Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_5.png';
import Vector6Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_6.png';
import Vector7Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_7.png';
import Vector8Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_8.png';
import Vector9Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_9.png';
import Vector10Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_10.png';
import Vector11Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_11.png';
import Vector12Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_12.png';
import Vector13Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_13.png';
import Vector14Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_14.png';
import Vector15Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_15.png';
import Vector16Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_16.png';
import Vector17Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_17.png';
import Vector18Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_18.png';
import Vector19Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_19.png';
import Vector20Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_20.png';
import Vector21Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_21.png';
import Vector22Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_22.png';
import Vector23Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_23.png';
import Vector24Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_24.png';
import Vector25Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_25.png';
import Vector26Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_26.png';
import Vector27Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_27.png';
import Vector28Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_28.png';
import Vector29Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_29.png';
import Vector30Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_30.png';
import Vector31Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_31.png';
import Vector32Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_32.png';
import Vector33Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_33.png';
import Vector34Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_34.png';
import Vector35Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_35.png';
import Vector36Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_36.png';
import Vector37Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_37.png';
import Vector38Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_38.png';
import Vector39Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_39.png';
import Group3513Image from 'src/assets/images/uduXDesktopPlayerWeb_Group_3513.png';
import Rectangle35844Image from 'src/assets/images/uduXDesktopPlayerWeb_Rectangle_3584_4.png';
import Rectangle35845Image from 'src/assets/images/uduXDesktopPlayerWeb_Rectangle_3584_5.png';
import Rectangle35846Image from 'src/assets/images/uduXDesktopPlayerWeb_Rectangle_3584_6.png';
import Rectangle35847Image from 'src/assets/images/uduXDesktopPlayerWeb_Rectangle_3584_7.png';
import Rectangle35848Image from 'src/assets/images/uduXDesktopPlayerWeb_Rectangle_3584_8.png';
import Rectangle3844Image from 'src/assets/images/uduXDesktopPlayerWeb_Rectangle_3844.png';
import Rectangle38451Image from 'src/assets/images/uduXDesktopPlayerWeb_Rectangle_3845.png';
import OmahLayNameTagMin1Image from 'src/assets/images/uduXDesktopPlayerWeb_Omah_Lay_Name_Tag_min_1.png';
import Xmlid146Image from 'src/assets/images/uduXDesktopPlayerWeb_XMLID_146_.png';
import Xmlid143Image from 'src/assets/images/uduXDesktopPlayerWeb_XMLID_143_.png';
import Xmlid142Image from 'src/assets/images/uduXDesktopPlayerWeb_XMLID_142_.png';
import Xmlid141Image from 'src/assets/images/uduXDesktopPlayerWeb_XMLID_141_.png';
import Vector40Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_40.png';
import Vector41Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_41.png';
import Vector42Image from 'src/assets/images/uduXDesktopPlayerWeb_Vector_42.png';
import { styled } from '@mui/material/styles';

const UduXDesktopPlayerWeb1 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1080px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const BurnaBoy = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `226.38px`,
  height: `285.01px`,
  left: `337px`,
  top: `873px`,
});

const Rectangle3543 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `185.66px`,
  height: `255.7px`,
  position: `absolute`,
  left: `20px`,
  top: `15px`,
});

const Rectangle3544 = styled('div')({
  background: `linear-gradient(10.379999999999995deg, rgba(173, 76, 29, 1) 31.83569240676532%, rgba(246, 183, 38, 1) 100.36540980040039%)`,
  width: `20.36px`,
  height: `236.15px`,
  position: `absolute`,
  left: `0px`,
  top: `34px`,
});

const Rectangle3591 = styled('div')({
  background: `linear-gradient(10.379999999999995deg, rgba(173, 76, 29, 1) 31.83569240676532%, rgba(246, 183, 38, 1) 100.36540980040039%)`,
  width: `20.36px`,
  height: `236.15px`,
  position: `absolute`,
  left: `206px`,
  top: `34px`,
});

const Rectangle3545 = styled('div')({
  background: `linear-gradient(81.11deg, rgba(171, 73, 28, 1) -17.002350027989586%, rgba(221, 174, 69, 1) 122.30061831479537%)`,
  width: `225.57px`,
  height: `74.92px`,
  position: `absolute`,
  left: `1px`,
  top: `195px`,
});

const Rectangle3546 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `226.38px`,
  height: `285.01px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Rectangle3584 = styled('img')({
  height: `162.86px`,
  width: `162.86px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `32px`,
  top: `20px`,
});

const AdekunleGold = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `226.38px`,
  height: `285.01px`,
  left: `588px`,
  top: `875px`,
});

const Rectangle35431 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `185.66px`,
  height: `255.7px`,
  position: `absolute`,
  left: `20px`,
  top: `15px`,
});

const Rectangle35441 = styled('div')({
  background: `linear-gradient(10.379999999999995deg, rgba(198, 21, 34, 1) 31.83569240676532%, rgba(3, 3, 4, 1) 100.36540980040039%)`,
  width: `20.36px`,
  height: `236.15px`,
  position: `absolute`,
  left: `0px`,
  top: `34px`,
});

const Rectangle3548 = styled('div')({
  background: `linear-gradient(10.379999999999995deg, rgba(198, 21, 34, 1) 31.83569240676532%, rgba(3, 3, 4, 1) 100.36540980040039%)`,
  width: `20.36px`,
  height: `236.15px`,
  position: `absolute`,
  left: `206px`,
  top: `34px`,
});

const Rectangle35451 = styled('div')({
  background: `linear-gradient(81.11deg, rgba(198, 21, 34, 1) -17.002350027989586%, rgba(3, 3, 4, 1) 122.30061831479537%)`,
  width: `225.57px`,
  height: `74.92px`,
  position: `absolute`,
  left: `1px`,
  top: `195px`,
});

const Rectangle35461 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `226.38px`,
  height: `285.01px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Rectangle35841 = styled('img')({
  height: `162.86px`,
  width: `162.86px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `32px`,
  top: `20px`,
});

const Rectangle3845 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `186px`,
  height: `256px`,
  position: `absolute`,
  left: `859px`,
  top: `889px`,
});

const Rectangle3846 = styled('div')({
  background: `linear-gradient(10.25deg, rgba(61, 102, 168, 1) 31.853855514447847%, rgba(145, 170, 199, 1) 100.3543291211145%)`,
  width: `20px`,
  height: `235px`,
  position: `absolute`,
  left: `1045px`,
  top: `910px`,
});

const Rectangle3847 = styled('div')({
  background: `linear-gradient(10.25deg, rgba(61, 102, 168, 1) 31.853855514447847%, rgba(145, 170, 199, 1) 100.3543291211145%)`,
  width: `20px`,
  height: `235px`,
  position: `absolute`,
  left: `840px`,
  top: `910px`,
});

const Rectangle3848 = styled('div')({
  background: `linear-gradient(81.2deg, rgba(32, 79, 157, 1) -17.05564659384036%, rgba(173, 192, 209, 1) 122.32575500700602%)`,
  width: `225px`,
  height: `74px`,
  position: `absolute`,
  left: `840px`,
  top: `1071px`,
});

const Rectangle3849 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `226px`,
  height: `285px`,
  position: `absolute`,
  left: `839px`,
  top: `875px`,
});

const Rectangle3850 = styled('img')({
  height: `163px`,
  width: `164px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `870px`,
  top: `895px`,
});

const DailyVibes1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0.64px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `111px`,
  height: `17px`,
  position: `absolute`,
  left: `359px`,
  top: `1081px`,
});

const BurnaBoyOxladeDavido = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 0.9)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0.4px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `178px`,
  height: `27px`,
  position: `absolute`,
  left: `359px`,
  top: `1108px`,
});

const DailyVibes2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0.64px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `111px`,
  height: `17px`,
  position: `absolute`,
  left: `609px`,
  top: `1081px`,
});

const LojayOxladeAmaaRaeRe = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 0.6)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0.4px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `178px`,
  height: `31px`,
  position: `absolute`,
  left: `609px`,
  top: `1108px`,
});

const DailyVibes3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0.64px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `111px`,
  height: `17px`,
  position: `absolute`,
  left: `859px`,
  top: `1081px`,
});

const KoffeeChrisBrownWstr = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 0.6)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0.4px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `178px`,
  height: `31px`,
  position: `absolute`,
  left: `859px`,
  top: `1108px`,
});

const BurnaBoy1 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `226.38px`,
  height: `285.01px`,
  left: `1089px`,
  top: `874px`,
});

const Rectangle35432 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `185.66px`,
  height: `255.7px`,
  position: `absolute`,
  left: `20px`,
  top: `15px`,
});

const Rectangle35442 = styled('div')({
  background: `linear-gradient(10.379999999999995deg, rgba(173, 76, 29, 1) 31.83569240676532%, rgba(246, 183, 38, 1) 100.36540980040039%)`,
  width: `20.36px`,
  height: `236.15px`,
  position: `absolute`,
  left: `0px`,
  top: `34px`,
});

const Rectangle35911 = styled('div')({
  background: `linear-gradient(10.379999999999995deg, rgba(173, 76, 29, 1) 31.83569240676532%, rgba(246, 183, 38, 1) 100.36540980040039%)`,
  width: `20.36px`,
  height: `236.15px`,
  position: `absolute`,
  left: `206px`,
  top: `34px`,
});

const Rectangle35452 = styled('div')({
  background: `linear-gradient(81.11deg, rgba(171, 73, 28, 1) -17.002350027989586%, rgba(221, 174, 69, 1) 122.30061831479537%)`,
  width: `225.57px`,
  height: `74.92px`,
  position: `absolute`,
  left: `1px`,
  top: `195px`,
});

const Rectangle35462 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `226.38px`,
  height: `285.01px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Rectangle35842 = styled('img')({
  height: `162.86px`,
  width: `162.86px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `32px`,
  top: `20px`,
});

const AdekunleGold1 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `226.38px`,
  height: `285.01px`,
  left: `1340px`,
  top: `876px`,
});

const Rectangle35433 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `185.66px`,
  height: `255.7px`,
  position: `absolute`,
  left: `20px`,
  top: `15px`,
});

const Rectangle35443 = styled('div')({
  background: `linear-gradient(10.379999999999995deg, rgba(198, 21, 34, 1) 31.83569240676532%, rgba(3, 3, 4, 1) 100.36540980040039%)`,
  width: `20.36px`,
  height: `236.15px`,
  position: `absolute`,
  left: `0px`,
  top: `34px`,
});

const Rectangle35481 = styled('div')({
  background: `linear-gradient(10.379999999999995deg, rgba(198, 21, 34, 1) 31.83569240676532%, rgba(3, 3, 4, 1) 100.36540980040039%)`,
  width: `20.36px`,
  height: `236.15px`,
  position: `absolute`,
  left: `206px`,
  top: `34px`,
});

const Rectangle35453 = styled('div')({
  background: `linear-gradient(81.11deg, rgba(198, 21, 34, 1) -17.002350027989586%, rgba(3, 3, 4, 1) 122.30061831479537%)`,
  width: `225.57px`,
  height: `74.92px`,
  position: `absolute`,
  left: `1px`,
  top: `195px`,
});

const Rectangle35463 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `226.38px`,
  height: `285.01px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Rectangle35843 = styled('img')({
  height: `162.86px`,
  width: `162.86px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `32px`,
  top: `20px`,
});

const Rectangle3851 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `186px`,
  height: `256px`,
  position: `absolute`,
  left: `1611px`,
  top: `890px`,
});

const Rectangle3852 = styled('div')({
  background: `linear-gradient(10.25deg, rgba(61, 102, 168, 1) 31.853855514447847%, rgba(145, 170, 199, 1) 100.3543291211145%)`,
  width: `20px`,
  height: `235px`,
  position: `absolute`,
  left: `1797px`,
  top: `911px`,
});

const Rectangle3853 = styled('div')({
  background: `linear-gradient(10.25deg, rgba(61, 102, 168, 1) 31.853855514447847%, rgba(145, 170, 199, 1) 100.3543291211145%)`,
  width: `20px`,
  height: `235px`,
  position: `absolute`,
  left: `1592px`,
  top: `911px`,
});

const Rectangle3854 = styled('div')({
  background: `linear-gradient(81.2deg, rgba(32, 79, 157, 1) -17.05564659384036%, rgba(173, 192, 209, 1) 122.32575500700602%)`,
  width: `225px`,
  height: `74px`,
  position: `absolute`,
  left: `1592px`,
  top: `1072px`,
});

const Rectangle3855 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `226px`,
  height: `285px`,
  position: `absolute`,
  left: `1591px`,
  top: `876px`,
});

const Rectangle3856 = styled('img')({
  height: `163px`,
  width: `164px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `1622px`,
  top: `896px`,
});

const DailyVibes11 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0.64px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `111px`,
  height: `17px`,
  position: `absolute`,
  left: `1111px`,
  top: `1082px`,
});

const BurnaBoyOxladeDavido1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 0.9)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0.4px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `178px`,
  height: `27px`,
  position: `absolute`,
  left: `1111px`,
  top: `1109px`,
});

const DailyVibes21 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0.64px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `111px`,
  height: `17px`,
  position: `absolute`,
  left: `1361px`,
  top: `1082px`,
});

const LojayOxladeAmaaRaeRe1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 0.6)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0.4px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `178px`,
  height: `31px`,
  position: `absolute`,
  left: `1361px`,
  top: `1109px`,
});

const DailyVibes31 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0.64px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `111px`,
  height: `17px`,
  position: `absolute`,
  left: `1611px`,
  top: `1082px`,
});

const KoffeeChrisBrownWstr1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 0.6)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0.4px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `178px`,
  height: `31px`,
  position: `absolute`,
  left: `1611px`,
  top: `1109px`,
});

const MaskGroup = styled('img')({
  height: `1163.51px`,
  width: `313px`,
  position: `absolute`,
  left: `625px`,
  top: `2246px`,
});

const Rectangle3830 = styled('div')({
  width: `350px`,
  height: `964px`,
  position: `absolute`,
  left: `-55px`,
  top: `0px`,
});

const Rectangle3441 = styled('div')({
  backgroundColor: `rgba(18, 18, 18, 1)`,
  width: `420px`,
  height: `170px`,
  position: `absolute`,
  left: `0px`,
  top: `910px`,
});

const Rectangle3442 = styled('img')({
  height: `170px`,
  width: `203px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `217px`,
  top: `910px`,
});

const Rectangle3825 = styled('div')({
  background: `linear-gradient(90deg, rgba(102, 39, 39, 0) 49.99999914861576%)`,
  width: `1920px`,
  height: `126px`,
  position: `absolute`,
  left: `0px`,
  top: `954px`,
});

const Rectangle3826 = styled('div')({
  border: `1px solid rgba(15, 15, 15, 1)`,
  boxSizing: `border-box`,
  width: `471px`,
  height: `56px`,
  position: `absolute`,
  left: `483px`,
  top: `21px`,
});

const Rectangle3828 = styled('div')({
  border: `1px solid rgba(15, 15, 15, 1)`,
  boxSizing: `border-box`,
  width: `1593px`,
  height: `1002px`,
  position: `absolute`,
  left: `305px`,
  top: `97px`,
});

const Line47 = styled('img')({
  height: `0px`,
  width: `295.5px`,
  position: `absolute`,
  left: `-1px`,
  top: `97px`,
});

const Home = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  position: `absolute`,
  left: `66px`,
  top: `139px`,
});

const Home1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `55px`,
  position: `absolute`,
  left: `66px`,
  top: `139px`,
});

const Discover = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `72px`,
  position: `absolute`,
  left: `66px`,
  top: `175px`,
});

const Group3518 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `3px`,
  height: `818px`,
  left: `292px`,
  top: `97px`,
});

const Group3517 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `3px`,
  height: `818px`,
  left: `0px`,
  top: `0px`,
});

const Group3516 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `3px`,
  height: `818px`,
  left: `0px`,
  top: `0px`,
});

const Group3515 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `3px`,
  height: `818px`,
  left: `0px`,
  top: `0px`,
});

const Rectangle3834 = styled('div')({
  border: `0.5px solid rgba(15, 15, 15, 1)`,
  boxSizing: `border-box`,
  width: `3px`,
  height: `818px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Rectangle3835 = styled('div')({
  backgroundColor: `rgba(251, 186, 18, 1)`,
  width: `3px`,
  height: `127px`,
  position: `absolute`,
  left: `0px`,
  top: `91px`,
});

const IconHomeWithRoofMade = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `17.97px`,
  height: `21px`,
  left: `33px`,
  top: `135px`,
});

const Group = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `17.97px`,
  height: `21px`,
  left: `0px`,
  top: `0px`,
});

const Vector = styled('img')({
  height: `10.09px`,
  width: `17.97px`,
  position: `absolute`,
  left: `0px`,
  top: `2px`,
});

const Vector1 = styled('img')({
  height: `3.08px`,
  width: `0.94px`,
  position: `absolute`,
  left: `9px`,
  top: `0px`,
});

const Vector2 = styled('img')({
  height: `2.77px`,
  width: `1.92px`,
  position: `absolute`,
  left: `9px`,
  top: `0px`,
});

const Vector3 = styled('img')({
  height: `2.77px`,
  width: `1.92px`,
  position: `absolute`,
  left: `7px`,
  top: `0px`,
});

const Vector4 = styled('img')({
  height: `7.99px`,
  width: `13.35px`,
  position: `absolute`,
  left: `2px`,
  top: `13px`,
});

const Rectangle3836 = styled('div')({
  backgroundColor: `rgba(15, 15, 15, 1)`,
  width: `295px`,
  height: `97px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Ellipse17593 = styled('img')({
  height: `62px`,
  width: `62px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `31px`,
  top: `18px`,
});

const IconXfce4Eyes = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `17.35px`,
  height: `14px`,
  left: `34px`,
  top: `178px`,
});

const Group1 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `17.35px`,
  height: `14px`,
  left: `0px`,
  top: `0px`,
});

const Vector5 = styled('img')({
  height: `9.87px`,
  width: `9.87px`,
  position: `absolute`,
  left: `7px`,
  top: `3px`,
});

const Vector6 = styled('img')({
  height: `7.52px`,
  width: `7.45px`,
  position: `absolute`,
  left: `1px`,
  top: `1px`,
});

const Vector7 = styled('img')({
  height: `8.62px`,
  width: `8.48px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector8 = styled('img')({
  height: `3.99px`,
  width: `3.99px`,
  position: `absolute`,
  left: `2px`,
  top: `2px`,
});

const Vector9 = styled('img')({
  height: `11.31px`,
  width: `11.31px`,
  position: `absolute`,
  left: `6px`,
  top: `3px`,
});

const Vector10 = styled('img')({
  height: `5.24px`,
  width: `5.24px`,
  position: `absolute`,
  left: `9px`,
  top: `6px`,
});

const YourLibrary = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `97px`,
  position: `absolute`,
  left: `67px`,
  top: `236px`,
});

const LikedSongs = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(251, 186, 18, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `97px`,
  position: `absolute`,
  left: `67px`,
  top: `272px`,
});

const RecentlyPlayed = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `67px`,
  top: `308px`,
});

const CreatePlaylist = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `66px`,
  top: `344px`,
});

const MyPlaylists = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `67px`,
  top: `405px`,
});

const RiffsRuns = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `31px`,
  top: `455px`,
});

const AfricanHeat = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `31px`,
  top: `491px`,
});

const GidiNights = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `30px`,
  top: `527px`,
});

const RunningOutOfPlaylist = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `29px`,
  top: `563px`,
});

const SaturdayWasAGoodDay = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `29px`,
  top: `599px`,
});

const GidiNights1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `28px`,
  top: `635px`,
});

const RiffsRuns1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `32px`,
  top: `671px`,
});

const AfricanHeat1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `32px`,
  top: `707px`,
});

const GidiNights2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `31px`,
  top: `743px`,
});

const RunningOutOfPlaylist1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `30px`,
  top: `779px`,
});

const SaturdayWasAGoodDay1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `30px`,
  top: `815px`,
});

const GidiNights3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `29px`,
  top: `851px`,
});

const RunningOutOfPlaylist2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `31px`,
  top: `887px`,
});

const SaturdayWasAGoodDay2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `31px`,
  top: `923px`,
});

const GidiNights4 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `30px`,
  top: `959px`,
});

const Line48 = styled('div')({
  border: `0.5px solid rgba(40, 40, 40, 1)`,
  width: `231px`,
  height: `0px`,
  position: `absolute`,
  left: `30px`,
  top: `216px`,
});

const IconMusicAlbum = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `17px`,
  height: `17px`,
  left: `33px`,
  top: `237px`,
});

const Vector11 = styled('img')({
  height: `17px`,
  width: `17px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const IconLoveFranceHeartN = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `17.64px`,
  height: `18px`,
  left: `33px`,
  top: `272px`,
});

const Group2 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `16.82px`,
  height: `17.4px`,
  left: `0px`,
  top: `1px`,
});

const Vector12 = styled('img')({
  height: `6.77px`,
  width: `7.27px`,
  position: `absolute`,
  left: `1px`,
  top: `1px`,
});

const Vector13 = styled('img')({
  height: `6.77px`,
  width: `7.27px`,
  position: `absolute`,
  left: `10px`,
  top: `9px`,
});

const Vector14 = styled('img')({
  height: `0.61px`,
  width: `0px`,
  position: `absolute`,
  left: `7px`,
  top: `9px`,
});

const Vector15 = styled('img')({
  height: `0.61px`,
  width: `0px`,
  position: `absolute`,
  left: `7px`,
  top: `11px`,
});

const Vector16 = styled('img')({
  height: `0px`,
  width: `0.61px`,
  position: `absolute`,
  left: `6px`,
  top: `10px`,
});

const Vector17 = styled('img')({
  height: `0px`,
  width: `0.61px`,
  position: `absolute`,
  left: `8px`,
  top: `10px`,
});

const Vector18 = styled('img')({
  height: `1.53px`,
  width: `1.53px`,
  position: `absolute`,
  left: `10px`,
  top: `0px`,
});

const Vector19 = styled('img')({
  height: `1.53px`,
  width: `1.53px`,
  position: `absolute`,
  left: `0px`,
  top: `16px`,
});

const Vector20 = styled('img')({
  height: `0.65px`,
  width: `0.65px`,
  position: `absolute`,
  left: `9px`,
  top: `8px`,
});

const Vector21 = styled('img')({
  height: `0.65px`,
  width: `0.65px`,
  position: `absolute`,
  left: `17px`,
  top: `7px`,
});

const Vector22 = styled('img')({
  height: `0.65px`,
  width: `0.65px`,
  position: `absolute`,
  left: `1px`,
  top: `0px`,
});

const Vector23 = styled('img')({
  height: `0.65px`,
  width: `0.65px`,
  position: `absolute`,
  left: `17px`,
  top: `16px`,
});

const Vector24 = styled('img')({
  height: `0.65px`,
  width: `0.65px`,
  position: `absolute`,
  left: `0px`,
  top: `9px`,
});

const Vector25 = styled('img')({
  height: `2.6px`,
  width: `2.8px`,
  position: `absolute`,
  left: `11px`,
  top: `5px`,
});

const Vector26 = styled('img')({
  height: `2.6px`,
  width: `2.8px`,
  position: `absolute`,
  left: `15px`,
  top: `0px`,
});

const Vector27 = styled('img')({
  height: `2.6px`,
  width: `2.8px`,
  position: `absolute`,
  left: `2px`,
  top: `11px`,
});

const Vector28 = styled('img')({
  height: `2.6px`,
  width: `2.8px`,
  position: `absolute`,
  left: `6px`,
  top: `15px`,
});

const IconAudio = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `16px`,
  height: `19.37px`,
  left: `34px`,
  top: `308px`,
});

const Vector29 = styled('img')({
  height: `19.37px`,
  width: `16px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector30 = styled('img')({
  height: `3.63px`,
  width: `4px`,
  position: `absolute`,
  left: `6px`,
  top: `12px`,
});

const IconMediaPlaylistApp = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `16px`,
  height: `16px`,
  left: `35px`,
  top: `345px`,
});

const Vector31 = styled('img')({
  height: `16px`,
  width: `16px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const IconSearch = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `16.5px`,
  height: `16.5px`,
  left: `247px`,
  top: `408px`,
});

const Vector32 = styled('img')({
  height: `16.5px`,
  width: `16.5px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector33 = styled('img')({
  height: `1.07px`,
  width: `1.07px`,
  position: `absolute`,
  left: `10px`,
  top: `10px`,
});

const IconSearch1 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `18px`,
  height: `18px`,
  left: `500px`,
  top: `40px`,
});

const Vector34 = styled('img')({
  height: `18px`,
  width: `18px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector35 = styled('img')({
  height: `1.17px`,
  width: `1.17px`,
  position: `absolute`,
  left: `11px`,
  top: `11px`,
});

const IconRecords = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `20px`,
  height: `20px`,
  left: `32px`,
  top: `405px`,
});

const Group3 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `20px`,
  height: `20px`,
  left: `0px`,
  top: `0px`,
});

const Vector36 = styled('img')({
  height: `2.5px`,
  width: `5px`,
  position: `absolute`,
  left: `5px`,
  top: `11px`,
});

const Vector37 = styled('img')({
  height: `20px`,
  width: `20px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Rectangle3832 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  width: `1920px`,
  height: `11px`,
  position: `absolute`,
  left: `0px`,
  top: `1069px`,
});

const Group3512 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `48px`,
  height: `41px`,
  left: `305px`,
  top: `28px`,
});

const Rectangle3837 = styled('div')({
  backgroundColor: `rgba(15, 15, 15, 1)`,
  width: `48px`,
  height: `41px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const IconArrowBackIos = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `32.58px`,
  height: `32.58px`,
  left: `8px`,
  top: `5px`,
});

const Vector38 = styled('img')({
  height: `32.58px`,
  width: `32.58px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector39 = styled('img')({
  height: `26.88px`,
  width: `15.84px`,
  position: `absolute`,
  left: `8px`,
  top: `3px`,
});

const Group3513 = styled('img')({
  height: `41px`,
  width: `48px`,
  position: `absolute`,
  left: `457px`,
  top: `110px`,
});

const WelcomeBack = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `700`,
  fontSize: `28px`,
  letterSpacing: `1.12px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `337px`,
  top: `396px`,
});

const CheersToTheWeekend = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `700`,
  fontSize: `28px`,
  letterSpacing: `1.12px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `338px`,
  top: `815px`,
});

const HeyAleem = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `92px`,
  position: `absolute`,
  left: `114px`,
  top: `39px`,
});

const BurnaBoy2 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `226.38px`,
  height: `285.01px`,
  left: `337px`,
  top: `482px`,
});

const Rectangle35434 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `185.66px`,
  height: `255.7px`,
  position: `absolute`,
  left: `20px`,
  top: `15px`,
});

const Rectangle35444 = styled('div')({
  background: `linear-gradient(10.379999999999995deg, rgba(173, 76, 29, 1) 31.83569240676532%, rgba(246, 183, 38, 1) 100.36540980040039%)`,
  width: `20.36px`,
  height: `236.15px`,
  position: `absolute`,
  left: `0px`,
  top: `34px`,
});

const Rectangle35912 = styled('div')({
  background: `linear-gradient(10.379999999999995deg, rgba(173, 76, 29, 1) 31.83569240676532%, rgba(246, 183, 38, 1) 100.36540980040039%)`,
  width: `20.36px`,
  height: `236.15px`,
  position: `absolute`,
  left: `206px`,
  top: `34px`,
});

const Rectangle35454 = styled('div')({
  background: `linear-gradient(81.11deg, rgba(171, 73, 28, 1) -17.002350027989586%, rgba(221, 174, 69, 1) 122.30061831479537%)`,
  width: `225.57px`,
  height: `74.92px`,
  position: `absolute`,
  left: `1px`,
  top: `195px`,
});

const Rectangle35464 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `226.38px`,
  height: `285.01px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Rectangle35844 = styled('img')({
  height: `162.86px`,
  width: `162.86px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `32px`,
  top: `20px`,
});

const AdekunleGold2 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `226.38px`,
  height: `285.01px`,
  left: `588px`,
  top: `484px`,
});

const Rectangle35435 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `185.66px`,
  height: `255.7px`,
  position: `absolute`,
  left: `20px`,
  top: `15px`,
});

const Rectangle35445 = styled('div')({
  background: `linear-gradient(10.379999999999995deg, rgba(198, 21, 34, 1) 31.83569240676532%, rgba(3, 3, 4, 1) 100.36540980040039%)`,
  width: `20.36px`,
  height: `236.15px`,
  position: `absolute`,
  left: `0px`,
  top: `34px`,
});

const Rectangle35482 = styled('div')({
  background: `linear-gradient(10.379999999999995deg, rgba(198, 21, 34, 1) 31.83569240676532%, rgba(3, 3, 4, 1) 100.36540980040039%)`,
  width: `20.36px`,
  height: `236.15px`,
  position: `absolute`,
  left: `206px`,
  top: `34px`,
});

const Rectangle35455 = styled('div')({
  background: `linear-gradient(81.11deg, rgba(198, 21, 34, 1) -17.002350027989586%, rgba(3, 3, 4, 1) 122.30061831479537%)`,
  width: `225.57px`,
  height: `74.92px`,
  position: `absolute`,
  left: `1px`,
  top: `195px`,
});

const Rectangle35465 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `226.38px`,
  height: `285.01px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Rectangle35845 = styled('img')({
  height: `162.86px`,
  width: `162.86px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `32px`,
  top: `20px`,
});

const Rectangle35436 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `186px`,
  height: `256px`,
  position: `absolute`,
  left: `859px`,
  top: `498px`,
});

const Rectangle35483 = styled('div')({
  background: `linear-gradient(10.25deg, rgba(61, 102, 168, 1) 31.853855514447847%, rgba(145, 170, 199, 1) 100.3543291211145%)`,
  width: `20px`,
  height: `235px`,
  position: `absolute`,
  left: `1045px`,
  top: `519px`,
});

const Rectangle3585 = styled('div')({
  background: `linear-gradient(10.25deg, rgba(61, 102, 168, 1) 31.853855514447847%, rgba(145, 170, 199, 1) 100.3543291211145%)`,
  width: `20px`,
  height: `235px`,
  position: `absolute`,
  left: `840px`,
  top: `519px`,
});

const Rectangle35456 = styled('div')({
  background: `linear-gradient(81.2deg, rgba(32, 79, 157, 1) -17.05564659384036%, rgba(173, 192, 209, 1) 122.32575500700602%)`,
  width: `225px`,
  height: `74px`,
  position: `absolute`,
  left: `840px`,
  top: `680px`,
});

const Rectangle35466 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `226px`,
  height: `285px`,
  position: `absolute`,
  left: `839px`,
  top: `484px`,
});

const Rectangle35846 = styled('img')({
  height: `163px`,
  width: `164px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `870px`,
  top: `504px`,
});

const DailyVibes12 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0.64px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `111px`,
  height: `17px`,
  position: `absolute`,
  left: `359px`,
  top: `690px`,
});

const BurnaBoyOxladeDavido2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 0.9)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0.4px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `178px`,
  height: `27px`,
  position: `absolute`,
  left: `359px`,
  top: `717px`,
});

const DailyVibes22 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0.64px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `111px`,
  height: `17px`,
  position: `absolute`,
  left: `609px`,
  top: `690px`,
});

const LojayOxladeAmaaRaeRe2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 0.6)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0.4px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `178px`,
  height: `31px`,
  position: `absolute`,
  left: `609px`,
  top: `717px`,
});

const DailyVibes32 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0.64px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `111px`,
  height: `17px`,
  position: `absolute`,
  left: `859px`,
  top: `690px`,
});

const KoffeeChrisBrownWstr2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 0.6)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0.4px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `178px`,
  height: `31px`,
  position: `absolute`,
  left: `859px`,
  top: `717px`,
});

const BurnaBoy3 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `226.38px`,
  height: `285.01px`,
  left: `1089px`,
  top: `483px`,
});

const Rectangle35437 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `185.66px`,
  height: `255.7px`,
  position: `absolute`,
  left: `20px`,
  top: `15px`,
});

const Rectangle35446 = styled('div')({
  background: `linear-gradient(10.379999999999995deg, rgba(173, 76, 29, 1) 31.83569240676532%, rgba(246, 183, 38, 1) 100.36540980040039%)`,
  width: `20.36px`,
  height: `236.15px`,
  position: `absolute`,
  left: `0px`,
  top: `34px`,
});

const Rectangle35913 = styled('div')({
  background: `linear-gradient(10.379999999999995deg, rgba(173, 76, 29, 1) 31.83569240676532%, rgba(246, 183, 38, 1) 100.36540980040039%)`,
  width: `20.36px`,
  height: `236.15px`,
  position: `absolute`,
  left: `206px`,
  top: `34px`,
});

const Rectangle35457 = styled('div')({
  background: `linear-gradient(81.11deg, rgba(171, 73, 28, 1) -17.002350027989586%, rgba(221, 174, 69, 1) 122.30061831479537%)`,
  width: `225.57px`,
  height: `74.92px`,
  position: `absolute`,
  left: `1px`,
  top: `195px`,
});

const Rectangle35467 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `226.38px`,
  height: `285.01px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Rectangle35847 = styled('img')({
  height: `162.86px`,
  width: `162.86px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `32px`,
  top: `20px`,
});

const AdekunleGold3 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `226.38px`,
  height: `285.01px`,
  left: `1340px`,
  top: `485px`,
});

const Rectangle35438 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `185.66px`,
  height: `255.7px`,
  position: `absolute`,
  left: `20px`,
  top: `15px`,
});

const Rectangle35447 = styled('div')({
  background: `linear-gradient(10.379999999999995deg, rgba(198, 21, 34, 1) 31.83569240676532%, rgba(3, 3, 4, 1) 100.36540980040039%)`,
  width: `20.36px`,
  height: `236.15px`,
  position: `absolute`,
  left: `0px`,
  top: `34px`,
});

const Rectangle35484 = styled('div')({
  background: `linear-gradient(10.379999999999995deg, rgba(198, 21, 34, 1) 31.83569240676532%, rgba(3, 3, 4, 1) 100.36540980040039%)`,
  width: `20.36px`,
  height: `236.15px`,
  position: `absolute`,
  left: `206px`,
  top: `34px`,
});

const Rectangle35458 = styled('div')({
  background: `linear-gradient(81.11deg, rgba(198, 21, 34, 1) -17.002350027989586%, rgba(3, 3, 4, 1) 122.30061831479537%)`,
  width: `225.57px`,
  height: `74.92px`,
  position: `absolute`,
  left: `1px`,
  top: `195px`,
});

const Rectangle35468 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `226.38px`,
  height: `285.01px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Rectangle35848 = styled('img')({
  height: `162.86px`,
  width: `162.86px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `32px`,
  top: `20px`,
});

const Rectangle3839 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `186px`,
  height: `256px`,
  position: `absolute`,
  left: `1611px`,
  top: `499px`,
});

const Rectangle3840 = styled('div')({
  background: `linear-gradient(10.25deg, rgba(61, 102, 168, 1) 31.853855514447847%, rgba(145, 170, 199, 1) 100.3543291211145%)`,
  width: `20px`,
  height: `235px`,
  position: `absolute`,
  left: `1797px`,
  top: `520px`,
});

const Rectangle3841 = styled('div')({
  background: `linear-gradient(10.25deg, rgba(61, 102, 168, 1) 31.853855514447847%, rgba(145, 170, 199, 1) 100.3543291211145%)`,
  width: `20px`,
  height: `235px`,
  position: `absolute`,
  left: `1592px`,
  top: `520px`,
});

const Rectangle3842 = styled('div')({
  background: `linear-gradient(81.2deg, rgba(32, 79, 157, 1) -17.05564659384036%, rgba(173, 192, 209, 1) 122.32575500700602%)`,
  width: `225px`,
  height: `74px`,
  position: `absolute`,
  left: `1592px`,
  top: `681px`,
});

const Rectangle3843 = styled('div')({
  border: `1px solid rgba(112, 112, 112, 1)`,
  boxSizing: `border-box`,
  width: `226px`,
  height: `285px`,
  position: `absolute`,
  left: `1591px`,
  top: `485px`,
});

const Rectangle3844 = styled('img')({
  height: `163px`,
  width: `164px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `1622px`,
  top: `505px`,
});

const DailyVibes13 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0.64px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `111px`,
  height: `17px`,
  position: `absolute`,
  left: `1111px`,
  top: `691px`,
});

const BurnaBoyOxladeDavido3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 0.9)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0.4px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `178px`,
  height: `27px`,
  position: `absolute`,
  left: `1111px`,
  top: `718px`,
});

const DailyVibes23 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0.64px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `111px`,
  height: `17px`,
  position: `absolute`,
  left: `1361px`,
  top: `691px`,
});

const LojayOxladeAmaaRaeRe3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 0.6)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0.4px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `178px`,
  height: `31px`,
  position: `absolute`,
  left: `1361px`,
  top: `718px`,
});

const DailyVibes33 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0.64px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `111px`,
  height: `17px`,
  position: `absolute`,
  left: `1611px`,
  top: `691px`,
});

const KoffeeChrisBrownWstr3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 0.6)`,
  fontStyle: `normal`,
  fontFamily: `Bw Modelica`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0.4px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `178px`,
  height: `31px`,
  position: `absolute`,
  left: `1611px`,
  top: `718px`,
});

const Group3557 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1581px`,
  height: `255px`,
  left: `311px`,
  top: `105px`,
});

const Group3514 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1581px`,
  height: `255px`,
  left: `0px`,
  top: `0px`,
});

const Rectangle38451 = styled('img')({
  height: `255px`,
  width: `1581px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const OmahLayNameTagMin1 = styled('img')({
  height: `112px`,
  width: `387px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `1161px`,
  top: `129px`,
});

const Text = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `114px`,
  height: `38px`,
  left: `41px`,
  top: `38px`,
});

const Xmlid146 = styled('img')({
  height: `38px`,
  width: `31.18px`,
  position: `absolute`,
  left: `83px`,
  top: `0px`,
});

const Xmlid143 = styled('img')({
  height: `32.14px`,
  width: `24.53px`,
  position: `absolute`,
  left: `29px`,
  top: `6px`,
});

const Xmlid142 = styled('img')({
  height: `22.84px`,
  width: `26.62px`,
  position: `absolute`,
  left: `0px`,
  top: `14px`,
});

const Xmlid141 = styled('img')({
  height: `22.84px`,
  width: `26.62px`,
  position: `absolute`,
  left: `56px`,
  top: `15px`,
});

const Line49 = styled('div')({
  border: `0.5px solid rgba(40, 40, 40, 1)`,
  width: `231px`,
  height: `0px`,
  position: `absolute`,
  left: `31px`,
  top: `444px`,
});

const IconSoundOn = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `18.75px`,
  height: `15px`,
  left: `180px`,
  top: `274px`,
});

const Group4 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `18.75px`,
  height: `15px`,
  left: `0px`,
  top: `0px`,
});

const Vector40 = styled('img')({
  height: `6.56px`,
  width: `0.94px`,
  position: `absolute`,
  left: `13px`,
  top: `4px`,
});

const Vector41 = styled('img')({
  height: `13.12px`,
  width: `2.81px`,
  position: `absolute`,
  left: `16px`,
  top: `1px`,
});

const Vector42 = styled('img')({
  height: `15px`,
  width: `9.37px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

function UduXDesktopPlayerWeb(props) {
  return (
    <UduXDesktopPlayerWeb1 className={props.className}>
      <BurnaBoy>
        <Rectangle3543></Rectangle3543>
        <Rectangle3544></Rectangle3544>
        <Rectangle3591></Rectangle3591>
        <Rectangle3545></Rectangle3545>
        <Rectangle3546></Rectangle3546>
        <Rectangle3584
          src={Rectangle3584Image}
          loading="lazy"
          alt={'Rectangle 3584'}
        />
      </BurnaBoy>
      <AdekunleGold>
        <Rectangle35431></Rectangle35431>
        <Rectangle35441></Rectangle35441>
        <Rectangle3548></Rectangle3548>
        <Rectangle35451></Rectangle35451>
        <Rectangle35461></Rectangle35461>
        <Rectangle35841
          src={Rectangle35841Image}
          loading="lazy"
          alt={'Rectangle 3584'}
        />
      </AdekunleGold>
      <Rectangle3845></Rectangle3845>
      <Rectangle3846></Rectangle3846>
      <Rectangle3847></Rectangle3847>
      <Rectangle3848></Rectangle3848>
      <Rectangle3849></Rectangle3849>
      <Rectangle3850
        src={Rectangle3850Image}
        loading="lazy"
        alt={'Rectangle 3850'}
      />
      <DailyVibes1>{`Daily Vibes 1 `}</DailyVibes1>
      <BurnaBoyOxladeDavido>
        {`Burna Boy, Oxlade, Davido, Tems Wizkid, Tiwa Savage..... `}
      </BurnaBoyOxladeDavido>
      <DailyVibes2>{`Daily Vibes 2 `}</DailyVibes2>
      <LojayOxladeAmaaRaeRe>
        {`Lojay, Oxlade, Amaa Rae, Rema, Omah Lay, SGawd.... `}
      </LojayOxladeAmaaRaeRe>
      <DailyVibes3>{`Daily Vibes 3 `}</DailyVibes3>
      <KoffeeChrisBrownWstr>
        {`Koffee, Chris Brown, WSTRN, Drake, Future, Burna Boy`}
      </KoffeeChrisBrownWstr>
      <BurnaBoy1>
        <Rectangle35432></Rectangle35432>
        <Rectangle35442></Rectangle35442>
        <Rectangle35911></Rectangle35911>
        <Rectangle35452></Rectangle35452>
        <Rectangle35462></Rectangle35462>
        <Rectangle35842
          src={Rectangle35842Image}
          loading="lazy"
          alt={'Rectangle 3584'}
        />
      </BurnaBoy1>
      <AdekunleGold1>
        <Rectangle35433></Rectangle35433>
        <Rectangle35443></Rectangle35443>
        <Rectangle35481></Rectangle35481>
        <Rectangle35453></Rectangle35453>
        <Rectangle35463></Rectangle35463>
        <Rectangle35843
          src={Rectangle35843Image}
          loading="lazy"
          alt={'Rectangle 3584'}
        />
      </AdekunleGold1>
      <Rectangle3851></Rectangle3851>
      <Rectangle3852></Rectangle3852>
      <Rectangle3853></Rectangle3853>
      <Rectangle3854></Rectangle3854>
      <Rectangle3855></Rectangle3855>
      <Rectangle3856
        src={Rectangle3856Image}
        loading="lazy"
        alt={'Rectangle 3856'}
      />
      <DailyVibes11>{`Daily Vibes 1 `}</DailyVibes11>
      <BurnaBoyOxladeDavido1>
        {`Burna Boy, Oxlade, Davido, Tems Wizkid, Tiwa Savage..... `}
      </BurnaBoyOxladeDavido1>
      <DailyVibes21>{`Daily Vibes 2 `}</DailyVibes21>
      <LojayOxladeAmaaRaeRe1>
        {`Lojay, Oxlade, Amaa Rae, Rema, Omah Lay, SGawd.... `}
      </LojayOxladeAmaaRaeRe1>
      <DailyVibes31>{`Daily Vibes 3 `}</DailyVibes31>
      <KoffeeChrisBrownWstr1>
        {`Koffee, Chris Brown, WSTRN, Drake, Future, Burna Boy`}
      </KoffeeChrisBrownWstr1>
      <MaskGroup src={MaskGroupImage} loading="lazy" alt={'Mask group'} />
      <Rectangle3830></Rectangle3830>
      {false && <Rectangle3441></Rectangle3441>}
      {false && (
        <Rectangle3442
          src={Rectangle3442Image}
          loading="lazy"
          alt={'Rectangle 3442'}
        />
      )}
      <Rectangle3825></Rectangle3825>
      <Rectangle3826></Rectangle3826>
      <Rectangle3828></Rectangle3828>
      <Line47 src={Line47Image} loading="lazy" alt={'Line 47'} />
      <Home>{`Home`}</Home>
      <Home1>{`Home`}</Home1>
      <Discover>{`Discover`}</Discover>
      <Group3518>
        <Group3517>
          <Group3516>
            <Group3515>
              <Rectangle3834></Rectangle3834>
            </Group3515>
          </Group3516>
        </Group3517>
        <Rectangle3835></Rectangle3835>
      </Group3518>
      <IconHomeWithRoofMade>
        <Group>
          <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
          <Vector1 src={Vector1Image} loading="lazy" alt={'Vector'} />
          <Vector2 src={Vector2Image} loading="lazy" alt={'Vector'} />
          <Vector3 src={Vector3Image} loading="lazy" alt={'Vector'} />
          <Vector4 src={Vector4Image} loading="lazy" alt={'Vector'} />
        </Group>
      </IconHomeWithRoofMade>
      <Rectangle3836></Rectangle3836>
      <Ellipse17593
        src={Ellipse17593Image}
        loading="lazy"
        alt={'Ellipse 17593'}
      />
      <IconXfce4Eyes>
        <Group1>
          <Vector5 src={Vector5Image} loading="lazy" alt={'Vector'} />
          <Vector6 src={Vector6Image} loading="lazy" alt={'Vector'} />
          <Vector7 src={Vector7Image} loading="lazy" alt={'Vector'} />
          <Vector8 src={Vector8Image} loading="lazy" alt={'Vector'} />
          <Vector9 src={Vector9Image} loading="lazy" alt={'Vector'} />
          <Vector10 src={Vector10Image} loading="lazy" alt={'Vector'} />
        </Group1>
      </IconXfce4Eyes>
      <YourLibrary>{`Your Library`}</YourLibrary>
      <LikedSongs>{`Liked Songs`}</LikedSongs>
      <RecentlyPlayed>{`Recently Played`}</RecentlyPlayed>
      <CreatePlaylist>{`Create Playlist`}</CreatePlaylist>
      <MyPlaylists>{`My Playlists `}</MyPlaylists>
      <RiffsRuns>{`Riffs & Runs  `}</RiffsRuns>
      <AfricanHeat>{`African Heat`}</AfricanHeat>
      <GidiNights>{`Gidi Nights`}</GidiNights>
      <RunningOutOfPlaylist>
        {`Running out of Playlist na....`}
      </RunningOutOfPlaylist>
      <SaturdayWasAGoodDay>{`Saturday was a Good Day`}</SaturdayWasAGoodDay>
      <GidiNights1>{`Gidi Nights`}</GidiNights1>
      <RiffsRuns1>{`Riffs & Runs  `}</RiffsRuns1>
      <AfricanHeat1>{`African Heat`}</AfricanHeat1>
      <GidiNights2>{`Gidi Nights`}</GidiNights2>
      <RunningOutOfPlaylist1>
        {`Running out of Playlist na....`}
      </RunningOutOfPlaylist1>
      <SaturdayWasAGoodDay1>{`Saturday was a Good Day`}</SaturdayWasAGoodDay1>
      <GidiNights3>{`Gidi Nights`}</GidiNights3>
      <RunningOutOfPlaylist2>
        {`Running out of Playlist na....`}
      </RunningOutOfPlaylist2>
      <SaturdayWasAGoodDay2>{`Saturday was a Good Day`}</SaturdayWasAGoodDay2>
      <GidiNights4>{`Gidi Nights`}</GidiNights4>
      <Line48></Line48>
      <IconMusicAlbum>
        <Vector11 src={Vector11Image} loading="lazy" alt={'Vector'} />
      </IconMusicAlbum>
      <IconLoveFranceHeartN>
        <Group2>
          <Vector12 src={Vector12Image} loading="lazy" alt={'Vector'} />
          <Vector13 src={Vector13Image} loading="lazy" alt={'Vector'} />
          <Vector14 src={Vector14Image} loading="lazy" alt={'Vector'} />
          <Vector15 src={Vector15Image} loading="lazy" alt={'Vector'} />
          <Vector16 src={Vector16Image} loading="lazy" alt={'Vector'} />
          <Vector17 src={Vector17Image} loading="lazy" alt={'Vector'} />
          <Vector18 src={Vector18Image} loading="lazy" alt={'Vector'} />
          <Vector19 src={Vector19Image} loading="lazy" alt={'Vector'} />
        </Group2>
        <Vector20 src={Vector20Image} loading="lazy" alt={'Vector'} />
        <Vector21 src={Vector21Image} loading="lazy" alt={'Vector'} />
        <Vector22 src={Vector22Image} loading="lazy" alt={'Vector'} />
        <Vector23 src={Vector23Image} loading="lazy" alt={'Vector'} />
        <Vector24 src={Vector24Image} loading="lazy" alt={'Vector'} />
        <Vector25 src={Vector25Image} loading="lazy" alt={'Vector'} />
        <Vector26 src={Vector26Image} loading="lazy" alt={'Vector'} />
        <Vector27 src={Vector27Image} loading="lazy" alt={'Vector'} />
        <Vector28 src={Vector28Image} loading="lazy" alt={'Vector'} />
      </IconLoveFranceHeartN>
      <IconAudio>
        <Vector29 src={Vector29Image} loading="lazy" alt={'Vector'} />
        <Vector30 src={Vector30Image} loading="lazy" alt={'Vector'} />
      </IconAudio>
      <IconMediaPlaylistApp>
        <Vector31 src={Vector31Image} loading="lazy" alt={'Vector'} />
      </IconMediaPlaylistApp>
      <IconSearch>
        <Vector32 src={Vector32Image} loading="lazy" alt={'Vector'} />
        <Vector33 src={Vector33Image} loading="lazy" alt={'Vector'} />
      </IconSearch>
      <IconSearch1>
        <Vector34 src={Vector34Image} loading="lazy" alt={'Vector'} />
        <Vector35 src={Vector35Image} loading="lazy" alt={'Vector'} />
      </IconSearch1>
      <IconRecords>
        <Group3>
          <Vector36 src={Vector36Image} loading="lazy" alt={'Vector'} />
          <Vector37 src={Vector37Image} loading="lazy" alt={'Vector'} />
        </Group3>
      </IconRecords>
      <Rectangle3832></Rectangle3832>
      <Group3512>
        <Rectangle3837></Rectangle3837>
        <IconArrowBackIos>
          <Vector38 src={Vector38Image} loading="lazy" alt={'Vector'} />
          <Vector39 src={Vector39Image} loading="lazy" alt={'Vector'} />
        </IconArrowBackIos>
      </Group3512>
      <Group3513 src={Group3513Image} loading="lazy" alt={'Group 3513'} />
      <WelcomeBack>{`Welcome Back!`}</WelcomeBack>
      <CheersToTheWeekend>{`Cheers to the Weekend `}</CheersToTheWeekend>
      <HeyAleem>{`Hey! Aleem`}</HeyAleem>
      <BurnaBoy2>
        <Rectangle35434></Rectangle35434>
        <Rectangle35444></Rectangle35444>
        <Rectangle35912></Rectangle35912>
        <Rectangle35454></Rectangle35454>
        <Rectangle35464></Rectangle35464>
        <Rectangle35844
          src={Rectangle35844Image}
          loading="lazy"
          alt={'Rectangle 3584'}
        />
      </BurnaBoy2>
      <AdekunleGold2>
        <Rectangle35435></Rectangle35435>
        <Rectangle35445></Rectangle35445>
        <Rectangle35482></Rectangle35482>
        <Rectangle35455></Rectangle35455>
        <Rectangle35465></Rectangle35465>
        <Rectangle35845
          src={Rectangle35845Image}
          loading="lazy"
          alt={'Rectangle 3584'}
        />
      </AdekunleGold2>
      <Rectangle35436></Rectangle35436>
      <Rectangle35483></Rectangle35483>
      <Rectangle3585></Rectangle3585>
      <Rectangle35456></Rectangle35456>
      <Rectangle35466></Rectangle35466>
      <Rectangle35846
        src={Rectangle35846Image}
        loading="lazy"
        alt={'Rectangle 3584'}
      />
      <DailyVibes12>{`Daily Vibes 1 `}</DailyVibes12>
      <BurnaBoyOxladeDavido2>
        {`Burna Boy, Oxlade, Davido, Tems Wizkid, Tiwa Savage..... `}
      </BurnaBoyOxladeDavido2>
      <DailyVibes22>{`Daily Vibes 2 `}</DailyVibes22>
      <LojayOxladeAmaaRaeRe2>
        {`Lojay, Oxlade, Amaa Rae, Rema, Omah Lay, SGawd.... `}
      </LojayOxladeAmaaRaeRe2>
      <DailyVibes32>{`Daily Vibes 3 `}</DailyVibes32>
      <KoffeeChrisBrownWstr2>
        {`Koffee, Chris Brown, WSTRN, Drake, Future, Burna Boy`}
      </KoffeeChrisBrownWstr2>
      <BurnaBoy3>
        <Rectangle35437></Rectangle35437>
        <Rectangle35446></Rectangle35446>
        <Rectangle35913></Rectangle35913>
        <Rectangle35457></Rectangle35457>
        <Rectangle35467></Rectangle35467>
        <Rectangle35847
          src={Rectangle35847Image}
          loading="lazy"
          alt={'Rectangle 3584'}
        />
      </BurnaBoy3>
      <AdekunleGold3>
        <Rectangle35438></Rectangle35438>
        <Rectangle35447></Rectangle35447>
        <Rectangle35484></Rectangle35484>
        <Rectangle35458></Rectangle35458>
        <Rectangle35468></Rectangle35468>
        <Rectangle35848
          src={Rectangle35848Image}
          loading="lazy"
          alt={'Rectangle 3584'}
        />
      </AdekunleGold3>
      <Rectangle3839></Rectangle3839>
      <Rectangle3840></Rectangle3840>
      <Rectangle3841></Rectangle3841>
      <Rectangle3842></Rectangle3842>
      <Rectangle3843></Rectangle3843>
      <Rectangle3844
        src={Rectangle3844Image}
        loading="lazy"
        alt={'Rectangle 3844'}
      />
      <DailyVibes13>{`Daily Vibes 1 `}</DailyVibes13>
      <BurnaBoyOxladeDavido3>
        {`Burna Boy, Oxlade, Davido, Tems Wizkid, Tiwa Savage..... `}
      </BurnaBoyOxladeDavido3>
      <DailyVibes23>{`Daily Vibes 2 `}</DailyVibes23>
      <LojayOxladeAmaaRaeRe3>
        {`Lojay, Oxlade, Amaa Rae, Rema, Omah Lay, SGawd.... `}
      </LojayOxladeAmaaRaeRe3>
      <DailyVibes33>{`Daily Vibes 3 `}</DailyVibes33>
      <KoffeeChrisBrownWstr3>
        {`Koffee, Chris Brown, WSTRN, Drake, Future, Burna Boy`}
      </KoffeeChrisBrownWstr3>
      <Group3557>
        <Group3514>
          <Rectangle38451
            src={Rectangle38451Image}
            loading="lazy"
            alt={'Rectangle 3845'}
          />
          <OmahLayNameTagMin1
            src={OmahLayNameTagMin1Image}
            loading="lazy"
            alt={'Omah Lay Name Tag-min 1'}
          />
        </Group3514>
        <Text>
          <Xmlid146 src={Xmlid146Image} loading="lazy" alt={'XMLID_146_'} />
          <Xmlid143 src={Xmlid143Image} loading="lazy" alt={'XMLID_143_'} />
          <Xmlid142 src={Xmlid142Image} loading="lazy" alt={'XMLID_142_'} />
          <Xmlid141 src={Xmlid141Image} loading="lazy" alt={'XMLID_141_'} />
        </Text>
      </Group3557>
      <Line49></Line49>
      <IconSoundOn>
        <Group4>
          <Vector40 src={Vector40Image} loading="lazy" alt={'Vector'} />
          <Vector41 src={Vector41Image} loading="lazy" alt={'Vector'} />
          <Vector42 src={Vector42Image} loading="lazy" alt={'Vector'} />
        </Group4>
      </IconSoundOn>
    </UduXDesktopPlayerWeb1>
  );
}

export default UduXDesktopPlayerWeb;
